FizzBuzz.WebApplication/Models/FizzBuzzModel.cs
using System.Web.UI.WebControls;

namespace FizzBuzz.WebApplication.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using PagedList;

    public class FizzBuzzModel
    {
        public int EnteredValue { get; set; }

        [Required(ErrorMessage = @"*Please enter {0}")]
        [RegularExpression("^[1-9][0-9]*$", ErrorMessage = "Please enter a positive integer")]
        [Range(typeof(int), "1", "1000", ErrorMessage = @"Please enter {0} between  {1} and {2}")]
        public int? Input { get; set; }

        public IPagedList<string> FizzBuzzList { get; set; }


    }
}

FizzBuzz.WebApplication/Controllers/FizzBuzzController.cs
using FizzBuzz.WebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FizzBuzz.BusinessLayer;
using PagedList;

namespace FizzBuzz.WebApplication.Controllers
{
    public class FizzBuzzController : Controller
    {
        private const int PageSize = 20;

        private readonly IBusinessLayer businessLayer;

        public FizzBuzzController(IBusinessLayer ibusinessLayer)
        {
            this.businessLayer = ibusinessLayer;
        }
        // GET: FizzBuzz

        [HttpGet]
        public ActionResult FizzBuzzList()
        {
            var fizzBuzzModel = new FizzBuzzModel();
            return this.View(fizzBuzzModel);
        }
        [HttpPost]
        public ActionResult FizzBuzzList(FizzBuzzModel model)
        {
            if (ModelState.IsValid)
            {
                model = this.GetFizzBuzzSequence(model.Input.Value, 1);
                ModelState.Clear();
            }

            return this.View("FizzBuzzList", model);
        }
        [HttpGet]
        public ActionResult ResultPage(int enteredValue, int pageNumber)
        {
            var model = this.GetFizzBuzzSequence(enteredValue, pageNumber);
            return this.View("FizzBuzzList", model);
        }
        private FizzBuzzModel GetFizzBuzzSequence(int inputNumber, int pageNumber)
        {
            var fizzBuzzList = this.businessLayer.GenerateFizzBuzzSequence(inputNumber);
            var model = new FizzBuzzModel { Input = inputNumber, EnteredValue = inputNumber, FizzBuzzList = fizzBuzzList.ToPagedList(pageNumber, PageSize) };
            return model;
        }

    }
}

FizzBuzz.WebApplication/Views/FizzBuzz/FizzBuzzList.cshtml
@model FizzBuzz.WebApplication.Models.FizzBuzzModel
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "FizzBuzzList";
}

<link href="~/Content/Fizz.css" rel="stylesheet" type="text/css" />
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using (Html.BeginForm("FizzBuzzList", "FizzBuzz"))
{

    @Html.ValidationSummary(true)
    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Input, "Enter a positive integer (Ranging 1-1000): ")
                @Html.TextBox("Input", Model.Input)
                @Html.ValidationMessageFor(model => model.Input)

            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Show Fizz Buzz List" />
            </td>
        </tr>
    </table>

}

@if (Model != null && Model.FizzBuzzList != null && Model.FizzBuzzList.Count > 0)
{
    <table class="table">

        @foreach (var sequence in Model.FizzBuzzList)
        {
            <tr>
                <td>
                    @{ var style = (sequence.Equals("fizz") || sequence.Equals("buzz")|| sequence.Equals("wizz") || sequence.Equals("wuzz")) ? sequence : string.Empty;
                        <span class="@style">@sequence</span>
                    }
                </td>
            </tr>
        }
    </table>
    @Html.PagedListPager((IPagedList<string>)Model.FizzBuzzList, pageNumber => Url.Action("ResultPage", new { Model.EnteredValue, pageNumber }),
        new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, LinkToFirstPageFormat = String.Format("<<"), LinkToPreviousPageFormat = String.Format("Previous"), LinkToNextPageFormat = String.Format("Next"), LinkToLastPageFormat = String.Format(">>"), MaximumPageNumbersToDisplay = 5 })}

FizzBuzz.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>